server:
  port: 8004

spring:
  application:
    name: cloud_provider_payment
  cloud:
    zookeeper:
      connect-string: 192.168.0.100:2181,192.168.0.100:2183,192.168.0.100:2182
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: mysql

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.alex.springcloud.entities   # 所有Entity别名类所在包