server:
  port: 83

spring:
  application:
    name: nacos-payment-order
  cloud:
      nacos:
        discovery:
          server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
