server:
  port: 3344

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AlexhahahaDrag/springcloud-config.git
          #uri: git@github.com:AlexhahahaDrag/springcloud-config.git
          search-paths:
            - springcloud-config
      label: master

eureka:
  client:
    register-with-eureka: true  #true表示将自己注册到eurekaserivce注册中心
    fetch-registry: true        #true表示从eureka service抓取已有的注册信息
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    prefer-ip-address: true
    instance-id: config3344

