server:
  port: 30018

spring:
  application:
    name: import_module
  datasource:
    url: jdbc:postgresql://10.10.30.199:5432/water?currentSchema=dataworks_sql
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update

#    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
#    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
#    url: jdbc:mysql://localhost:3306/dataworks?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
#    username: root
#    password: mysql

mybatis-plus:
  global-config:
    db-config:
      #驼峰下划线转换
      db-column-underline: true
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)
logging:
  level:
    com.alex.springcloud.mapper: debug

