server:
  port: 8011

spring:
  application:
    name: cloud-provider-payment-hystrix
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: mysql

eureka:
  client:
    register-with-eureka: true  #true表示将自己注册到eurekaserivce注册中心
    fetch-registry: true        #true表示从eureka service抓取已有的注册信息
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    prefer-ip-address: true
    instance-id: payment8011

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.alex.springcloud.entities   # 所有Entity别名类所在包