server:
  port: 80

spring:
  application:
    name: cloud_consumerCS_order
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        service-name: #{spring.application.name}