server:
  port: 9500

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建的路由功能，利用微服务进行路由
      routes:
        - id: payment_routh #payment_routh 路由的id，没有固定的规则但是要求是唯一，建议用服务名
          uri: http://localhost:8010        #匹配后提供服务的路由地址
          #url: lb://cloud-provider-payment-hystrix #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**
        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8010        #匹配后提供服务的路由地址
          #uri: lb://cloud-provider-payment-hystrix #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/create        # 断言，路径相匹配的进行路由
              #- After=2020-02-21T15:51:37.485+08:00[Asia/Shanghai]
              #- Cookie=username,zzyy
              #- Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式
eureka:
  client:
    register-with-eureka: true  #true表示将自己注册到eurekaserivce注册中心
    fetch-registry: true        #true表示从eureka service抓取已有的注册信息
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    prefer-ip-address: true
    instance-id: gateway
